Add tuples and patterns to ast and a parser for them
i-pankrat/jaml pull request #18
Opened 2024-01-04 19:33 UTC by DrumovMax

Изменено аст добавлением кортежей и паттернов. Изменен парсер и исправлены баги в инференсере после изменения аст.

2024-01-04 19:39 UTC, DrumovMax commented
Сделал ПР пока в ветку с фиксом замыканий, а не в jaml чтобы разобраться потом по очередности что туда пушить

2024-01-04 20:02 UTC, DrumovMax commented
"Фикс" инференсера не покрывает все случаи паттер-матчинга. Своего рода заглушка чтобы сбилдить :)

2024-01-05 11:20 UTC, i-pankrat commented
Давай тогда, чтобы не мусорить пока что в PR к Дмитрию Сергеевичу все PR сделаем в ветку jaml-dev, и как доделаем до более менее нормальнго состояние кортежи вплоть до anf из jaml-dev сделаем PR в jaml. 

У меня никаких вопросов нет по данному PR, мне всё нравится. Единственное я бы добавил несколько тестов для let in, let rec in, я их не увидел

2024-01-05 11:23 UTC, i-pankrat requested changes
Добавить чуть больше тестов для кортежей в let in, let rec in

2024-01-05 12:48 UTC, i-pankrat commented
Супир

2024-01-05 12:49 UTC, merged