Lambda lifting tuples
i-pankrat/jaml pull request #22
Opened 2024-02-17 18:15 UTC by DrumovMax

2024-02-18 05:46 UTC, i-pankrat requested changes
Конечно, не уверен, что работу по избавлению от патернов нужно делать на этой стадии. Но пускай пока что будет здесь.

Нужно поправить тесты.

2024-02-18 05:46 UTC, i-pankrat commented on JaML/lib/lambdalift.ml
> +      List.fold_right
Почему не просто fold? Разве здесь нужен fold_right?

2024-02-18 05:46 UTC, i-pankrat commented on JaML/lib/lambdalift.ml
> +      List.fold_right
Аналогично, почему fold_right?

2024-02-18 05:46 UTC, i-pankrat commented on JaML/lib/lambdalift.ml
> +        List.fold_left
почему List.fold_left, а не List.fold?

2024-02-18 05:46 UTC, i-pankrat commented on JaML/lib/tests/lambdalift_tests.ml
> +(** Tests for tuples *)
Добавил тесты, их нужно поправить, и по возможности добавить новые

2024-02-18 05:46 UTC, i-pankrat commented on JaML/lib/lambdalift.ml
> +    let new_id = genid "#cortege_out" in
Если мы вдруг захотим изменить "#cortege_out" на что-то иное, то нам придётся это менять во всех местах использования. По этой причине мне кажется, что лучше вынести let CORTEGE_GENID = "#cortege_out", можно и другое название рассмотреть

2024-02-18 05:46 UTC, i-pankrat commented on JaML/lib/lambdalift.ml
> +          pat_lst
выглядит круто, но я пока не совсем понял

2024-02-19 17:48 UTC, DrumovMax commented on JaML/lib/lambdalift.ml
> +      List.fold_right
Исправил

2024-02-19 17:48 UTC, DrumovMax commented on JaML/lib/lambdalift.ml
> +      List.fold_right
Исправил

2024-02-19 17:48 UTC, DrumovMax commented on JaML/lib/lambdalift.ml
> +        List.fold_left
Исправил

2024-02-19 17:48 UTC, DrumovMax commented on JaML/lib/tests/lambdalift_tests.ml
> +(** Tests for tuples *)
Поправил и добавил

2024-02-19 17:50 UTC, DrumovMax commented on JaML/lib/lambdalift.ml
> +    let new_id = genid "#cortege_out" in
вопрос хороший, нужно ли это сделать по итогу?
Это используется в двух местах такое название, как и название #wildcard.
На размышление

2024-02-19 18:27 UTC, i-pankrat requested changes
Всё очень круто, внёс незначительные предложения к исправлению

2024-02-19 18:27 UTC, i-pankrat commented on JaML/lib/lambdalift.ml
> +(** The function is used to get rid of tuples in let in constructors and in arguments.
Думаю, что лучше конструкторы называть явно, как они у нас есть TLetIn, например. Нужно время чтобы понять выражение ... in let in ..., кда лучше in TLetIn

2024-02-19 18:27 UTC, i-pankrat commented on JaML/lib/lambdalift.ml
> +(** The function is used to get rid of tuples in let constructors.
TLet

2024-02-19 18:27 UTC, i-pankrat commented on JaML/lib/tests/lambdalift_tests.ml
> +;;
Дубликат теста выше

2024-02-19 18:27 UTC, i-pankrat commented on JaML/lib/tests/lambdalift_tests.ml
> +        let #tuple_out1 = a in
Я добавил новый тест, если не потребует слишком много усилий сделать так, чтобы в данном случае #tuple_out1 не создавался, а вместо него использовалась бы уже созданная переменная 'a', то было бы круто. Если не получится, то можно оставить этот тест так, как он имеется сейчас. Это не критичное изменение.

2024-02-19 18:29 UTC, i-pankrat commented on JaML/lib/lambdalift.ml
> +    let new_id = genid "#cortege_out" in
Пускай останется пока что в планы на "дальнейший" рефакторинг

2024-02-20 15:37 UTC, i-pankrat approved these changes
LGFM, thank you

2024-02-20 15:39 UTC, merged