Implementation Alpha conversion, Closure conversion
i-pankrat/jaml pull request #8
Opened 2023-10-31 01:00 UTC by DrumovMax

2023-10-31 01:07 UTC, DrumovMax commented on JaML/lib/alpha.ml
> +  | None -> x
Потом поправлю

2023-11-02 13:16 UTC, i-pankrat requested changes
1. Вообще было бы неплохо сделать создание новых имён с помощью StateMonad, возможно, я когда-то её всё же сделаю)))
2. Был бы благодарен, если бы над каждым тестом было написано в синтаксисе нашего языка, что мы имеем, и что хотим получить. Сам буду стараться так делать. Кажется, что с такой подсказкой тест воспринимать куда проще, нежели чем эти конструкторы
3. Я несколько недоревьюил тесты по причину пункта 2. Плюс надо будет посмотреть мне ещё подбронее `clousure.ml`

Но в целом всё круто, мне очень нравится. Тесты похожи на правду

2023-11-02 13:16 UTC, i-pankrat commented on JaML/lib/counter.mli
> +  val count_next : unit -> int
нужна ли эта функция?

2023-11-02 13:16 UTC, i-pankrat commented on JaML/lib/lambdalift.ml
> +          ~f:(fun (env, stms) (key, stmt) -> EnvM.remove env key, stmt :: stms)
мы удаляем из `env` всё, что добавили для выноса, чтобы не использовать это в следующих летах?

2023-11-02 13:16 UTC, i-pankrat commented on JaML/lib/lambdalift.ml
> +let run_lambda_lift_statements =
кажется, что у нас так много однотипных функций для запуска тестов, может быть нам в папочке tests создать какой-то модуль дли одной единой функции печати тестов?

2023-11-03 21:44 UTC, DrumovMax commented on JaML/lib/counter.ml
> +    x ^ string_of_int !count
Поправил

2023-11-03 21:44 UTC, DrumovMax commented on JaML/lib/counter.ml
> +  let count_next () =
Убрал

2023-11-03 21:45 UTC, DrumovMax commented on JaML/lib/closure.ml
> +    let expr, known, env = closure_expr env known other in
Поправил

2023-11-03 21:46 UTC, DrumovMax commented on JaML/lib/closure.ml
> +let put_diff_arg diff acc =
Добавил описание

2023-11-03 21:46 UTC, DrumovMax commented on JaML/lib/closure.ml
> +  List.fold_left diff ~init:acc ~f:(fun (expr, expr_ty) var ->
Поправил

2023-11-03 21:47 UTC, DrumovMax commented on JaML/lib/closure.ml
> +  | _ -> NameS.empty
Добавил.

2023-11-03 21:47 UTC, DrumovMax commented on JaML/lib/closure.ml
> +end
Написал

2023-11-03 21:47 UTC, DrumovMax commented on JaML/lib/closure.ml
> +module EnvM = struct
Описал что из себя представляет env

2023-11-03 21:48 UTC, DrumovMax commented on JaML/lib/lambdalift.ml
> +end
Я думаю модуль не стоит выносить отдельно. Обернул модуль в модуль, чтобы писать короче)

2023-11-03 21:49 UTC, DrumovMax commented on JaML/lib/lambdalift.ml
> +;;
Написал короче некуда)

2023-11-03 21:49 UTC, DrumovMax commented on JaML/lib/closure.ml
> +  | TVar (x, ty) ->
Частично применил

2023-11-03 21:49 UTC, DrumovMax commented on JaML/lib/counter.mli
> +  val count_next : unit -> int
Убрал

2023-11-03 21:51 UTC, DrumovMax commented on JaML/lib/lambdalift.ml
> +          ~f:(fun (env, stms) (key, stmt) -> EnvM.remove env key, stmt :: stms)
Да, хранить в env нужно только чтобы донести функции на вынос, до нужного места и там их оставить. Больше нам они не нужны.

2023-11-05 09:27 UTC, closed without merging